### ISSUE TITLE
iokan random reboots

### ISSUE THREAD

**Issue by hulakdar** [LegacyXperia/local_manifests#1012]
After a few days of stable and quick work of last nightly build of LXCM12.1 it started rebooting randomly. it even reboots while rebooting X-D
reboots at least 5-7 times a day.
bugreport attached. 
[bugreport.zip](https://github.com/LegacyXperia/local_manifests/files/75727/bugreport.zip)

**Comment by niks255** [comment]
I've fixed this issue in my builds. It happens because zRam disk is compressed with LZ4. I disabled LZ4 compression and haven't had any reboots since then. To do this you need to cherry-pick this https://github.com/niks255/android_kernel_semc_msm7x30/commit/d65c5fb4dfb7cd2002e081a2b9ca2f2bf8c9acd9 and build your kernel. My kernel won't work for you cause I use emulated storage.
