### ISSUE TITLE
[CM13][anzu]"XYZ was closed"-messages in a loop

### ISSUE THREAD

**Issue by ghost** [LegacyXperia/local_manifests#1044]
Hi guys,

yesterday after I rebooted the phone because an app (OSMand) always closed itself (it worked some days before), the phone started to pop up serveral "xyz was closed" (trebuchet, google play services, music, com.android.phone) messages which opened again and again in a loop without an ending.
First i tried to reset it to factory default, which didn't helped at all and today i tried to reinstall LX13 completely (deleted and added the partition on the sd-card, flashed boot.img, full factory reset, wipe cache, wipe system partition, sideloaded cm13 and minigapps).
After the first boot the phone seemed to work normal for 10 to 30 seconds BUT all my apps were still installed. After those couple of seconds the phone started to show the "was closed" stuff again. The app in the background I could start before the messages seemed to work fine, but I couldn't do nearly anything in it because of the messages.

How can I "reset" the phone completely, i.e. also remove all apps? I tried it three times now with the installing Marshmallow guide with the same result.

Sorry, I don't know how to get some logs in this situation :/

Thanks for your help
Markus

**Comment by gabri-hell** [comment]
Hi, have you tried to disable automatic restoration of applications and parameters ?

> Parameters > Backup & reset > Automatic restoration

Seems to be a buggy app "XYZ", list and remove it next time...

**Comment by ghost** [comment]
Hi,

thanks for your post. I managed to get into the Backup & reset menu before the phone startet to pop up the messages - "Save my data" is disabled and i have not configured an account at all. It dosen't seems like the data is restored.

Am I doing somithing wrong? Should all data be gone after the procedure I described in Post #1?

And: The messages seems to differ, sometime others are poping up. Now: "com.android.phone, com.android.acore, Google services framework, and a couple of (preinstalled) apps like clock, SMS/MMS, music" etc. etc.

**Comment by gabri-hell** [comment]
Just in case, verify your downloaded ROM with md5 checksum.
To partition your SD card, on Windows try [AOMEI](http://download.cnet.com/AOMEI-Partition-Assistant-Standard-Edition/3000-18512_4-75118871.html?part=dl-&subj=dl&tag=button) instead of Partition Wizard which has tendency to make "wackies" alignment and sometimes lets a tiny and lost second partition before or after your primary inactive partition.
I hope that one day partitioning softwares will better manage flash memories because for the moment it's not glorious... ADB seems to be the most effective solution but not friendly.
I confess that I don't understand why your app are always present on reboot after full factory reset and wiping data. If possible try logcat with [adb](http://developer.android.com/tools/help/logcat.html).

**Comment by ghost** [comment]
Thanks ones more for your help. Like you suggested, I checked the md5 sum and downloaded AOMEI (before i partitioned in Ubuntu with fdisk) and tried it two or three times more to fully wipe the system and install it afterwards. Then I tried to format the SD-card on my own (before I let it unformated) but none of the programs (fdisk, AOMEI, Partition Wizard, Windows build in, and I put it in another Android phone an tried to format it) was able to do it. So i guessed, that the SD-card/it's controller etc. was somehow defect so I bought a new card. With the new card it was straight forward :/

So likely the SD card was/is defect. If it has something to do with LX would be a question :)

**Comment by gabri-hell** [comment]
Legendary fragility of SD cards... but it's true too that on Android 6.0, they are much more "stressed" because of emulated storage. Reverse of the medal but so nice to have no more error message for insufficient memory. Here the importance of choosing a UHS fast and quality card.
To format rebel cards, sometimes [SD Formater](https://www.sdcard.org/downloads/formatter_4/index.html) performs miracles ! Use full overwrite and size adjustment formatting and later with AOMEI use partition check option and search for bad sectors.
