### ISSUE TITLE
Airplane mode problem in 2G

### ISSUE THREAD

**Issue by pimo73** [LegacyXperia/local_manifests#138]
When is 2G on after switch off Airplane mode can not connect to network without restart telephone, cm-10.2_urushi-LX-20131108-NIGHTLY soft

**Comment by ghost** [comment]
It's working on my Arc S.

**Comment by mikeNG** [comment]
It's a known bug that happens at random times and not on all networks/phones, making it impossible for me to debug/test/fix. This hasn't been fixed since cm-10.1 was out and probably will never be fixed.

**Comment by mikeNG** [comment]
try latest cm11 build

**Comment by sidharthgtm** [comment]
i recently installed Baseband 86 , and from then i am not experiencing this bug.

**Comment by Norde** [comment]
I confirm that sidharthgtm say, this problem seems to be intimately linked to baseband.

With Xperia Arc S, this bug occurs with basebands ≤ 77.
With baseband 82 or 85 (and higher, as indicated by sidharthgtm), this bug no longer appears.

For those concerned, a collection of baseband for Xperia Arc (LT15i and LT18i) is available here: http://forum.xda-developers.com/showthread.php?t=1688049

**Comment by fqdb** [comment]
For Hallon and Haida baseband .77 is the latest AFAIK. Are Anzu basebands compatible with all mogami devices?

**Comment by mikeNG** [comment]
@sdk16420 no, cross-flashing basebands is not recommended
