### ISSUE TITLE
ANT+ does not work

### ISSUE THREAD

**Issue by mikeNG** [LegacyXperia/local_manifests#158]
We need to write support code for wl12xx from scratch in order to have ANT+ working with bluedroid.
Marked as wontfix until someone writes the code.

**Comment by kitabema** [comment]
A bit off topic, but does wl1271 (i.e. in Xperia Neo (hallon)) - and the available driver - support BLE? In case ANT+ support would not be that important - at least for me.

**Comment by mikeNG** [comment]
The chip supports BLE but I'm not sure about the current drivers. I don't have a BLE device to test.

**Comment by JanPenicka** [comment]
Hi,
is some change, regarding functionality ANT+? Support ANT+ is very important for me:-) = I use Heart Rate Monitor for sport...

I can possibly help with testing on the phones: Xperia Arc S (Anzu/ LT18i) and Sony Ericsson Live with Walkman (Coconut).

**Comment by kitabema** [comment]
@JanPenicka 

Maybe you can convince this guy

http://forum.xda-developers.com/member.php?u=580618

who seems to be the author of ANT+ enabling for phones with bcm4339 chips to support wl12xx chips as well (though I would prefer open source drivers for our phones).

(I currently have no BLE or ANT+ gadget but I am considering buying one.)

**Comment by mikeNG** [comment]
There's nothing I can do for this since I don't have a BLE or an ANT device.
I don't have in my plans to buy any of these gadgets. If the community decides to donate some gadgets for testing, I can do some proper testing.

**Comment by MardonHH** [comment]
![ant](https://cloud.githubusercontent.com/assets/1421697/4157887/1d62387c-3484-11e4-98e7-b07cf8a1d0a1.jpg)
Compiling a testbuild with ANT+ for Anzu
I also dont have a device to test ANT like mike,
so I need someone to test it when build process finished

**Comment by mikeNG** [comment]
It won't work, I looked into it today. We need to reimplement the wl12xx ANT code from bluez to bluedroid and also modify the BT vendor lib. A lot of work plus I don't have an ANT device to test, so I'm not going to work on it yet.

**Comment by MardonHH** [comment]
ANT+ testbuild for ANZU
cm-11-20140905-ANT+UNOFFICIAL-LegacyXperia-anzu.zip
https://www.androidfilehost.com/?fid=23622183712467182

**Comment by rohanmartin** [comment]
The Bluedroid patch for ANT+ support is now available. I will update my branches to CM12.1 and it should be easy to pick up. I have a Ray, ANT+ and BLE devices.

http://forum.xda-developers.com/showpost.php?p=55538434&postcount=3

wl12xx won't support ANT+ and BLE at the same time, but the functionality is flashed to the chip at runtime so in theory something could be done for switching between the two - but that's a lot of new work.

**Comment by aberus** [comment]
After this years is there any new information about ANT+. If I have to choose between ANT+ and BLE, I would settle for ANT+.

**Comment by mirh** [comment]
Afaik ANT relies on bluetooth HCI. 
In turns [wilink6](http://processors.wiki.ti.com/images/5/5e/WL1271_Solution_Hardware.pdf#page=11) should support the thing via UART, SPI and SDIO. 
I know the later was at least used for something wifi in cm10 days. The middle, never heard about, but it's now supported by [mainline](https://patchwork.kernel.org/patch/9235983/). While the first.. Idk, at least on [moto G](https://forum.xda-developers.com/hardware-hacking/hardware/ref-devices-ant-hardware-t2879990/page4#post67580436) seems to work at least up to cm13. 

There doesn't seem any particular roadbloack for the feature, aside of cherry-picking [ant-wireless ](https://github.com/ant-wireless) repos, since AOSP never merged back their code (and for as much as I know, current lineageos's is either dropped or outdated)

**Comment by ghost** [comment]
Will it also work for CM14.1? Can anyone please create build for satsuma with ANT+ either CM13 or CM14.1?
