### ISSUE TITLE
GPS doesn't turn off

### ISSUE THREAD

**Issue by mikeNG** [LegacyXperia/local_manifests#161]
After using an app with GPS, GPS still seems to consume battery power.
The app is closed and GPS is deactivated. Although battery power is decreasing. In the power consumption overview (battery -> point on graph) it can be seen that GPS is still active.

Simplest solution: never deactivate gps. Android itself manages the gps better than if you enable/disable it all the time.

**Comment by mspacek** [comment]
I recently started observing this as well. Rebooting seems to fix it for me. I would think this is a rather important issue, given that GPS is especially often used when far away from any power source. This is exactly the time when I'm extra careful about battery use. Ironically, being careful in this case (turning off GPS when not needed) results in the opposite effect.

It's a security issue as well. I don't want to leave GPS or other location tracking enabled when I don't need those features.

**Comment by mikeNG** [comment]
This is a bug since summer 2012 and cm10, nobody has managed to fix it so far. I doubt it will get fixed (at least by me) since it's not on my todo list.

**Comment by MardonHH** [comment]
system\etc\permissions\android.hardware.location.gps.xml
is missing (tested cm10.2 15.12.2013 - ANZU - LT18i)
also some other permissions.xml files are missing

**Comment by mikeNG** [comment]
Possible fix http://review.cyanogenmod.org/71199

**Comment by mikeNG** [comment]
Can someone test if this is resolved in the latest build?

**Comment by psyke83** [comment]
mikeNG,

device: smultron
build: 20140907
GPS setting: device only

Procedure:
1. Open GPS Status, leaving open for ~30 seconds
2. Close GPS Status
3. Check Battery graph (GPS shown as active for ~30 seconds)
4. Leave phone idle for ~2 minutes
5. Check Battery graph

Result: no further GPS activity shown on graph (only the ~30 second block is visible)

Did I need to manually turn off GPS via the quick settings panel/settings app in order to trigger the bug? I'm not sure if that was a factor for the bug to manifest.

**Comment by psyke83** [comment]
Repeating the testcase with one difference (which I guess would have triggered this bug):
2. Close GPS Status _and_ disable GPS via QS menu.

Result: the same as before, no further GPS usage.

**Comment by azakosath** [comment]
Unfortunately it's still there :(
I enabled GPS by mistake from the quick access ribbon and disabled instantly. But, when I checked BBS after a couple of hours, GpsLocationProvider wakelock was there.
