### ISSUE TITLE
[10.2] battery drained in few hours with sms app

### ISSUE THREAD

**Issue by piotrwie** [LegacyXperia/local_manifests#171]
![screenshot_2013-11-27-14-27-03](https://f.cloud.github.com/assets/2567691/1637527/f6df3a6a-57ed-11e3-9d47-0648a92f9aee.png)
build 131112, mango
yesterday morning wife had sent me an mms. i didn't receive it until 2pm. but then i noticed battery level of ca 30%. in the morning it was full. I've checked batt stats and strangely android reported sms process consumed a lot of battery load.
i'll try to reproduce later.
i've got in country roaming on, operator forced to the roamed one, 2g network forced.
The mms suddenly came when I've switched on data transmission at 2pm to check email. (in previous versions mms and data transmission were not related).

**Comment by piotrwie** [comment]
update.
again, similar story, this time after clearing data partition (fresh cm10.2, 131112).
![screenshot_2013-11-29-11-32-36](https://f.cloud.github.com/assets/2567691/1644379/a51915ac-58e2-11e3-93db-511c1860edb6.png)

**Comment by mikeNG** [comment]
please provide logs

**Comment by piotrwie** [comment]
ok, as soon as toblem occurs i'll get dumpsys and some wakelock dumps. at that time i didnt know how to do this and catlog did not show anything strange...

**Comment by nezirus** [comment]
Please check issue #330, maybe this problem is MMS related.

**Comment by mikeNG** [comment]
No logs

**Comment by piotrwie** [comment]
I'll probably not be able to deliver logs as I switched to other rom... This problem occured when incoming mms was queued at provider, but due to unknown reasons it was not transferred (auto-pull was on) to my mobile. Twice the same situation in few days (month ago). There was no indication of incoming mms.
Battery was drained in few hours back then.

**Comment by mspacek** [comment]
@mikeNG, I just updated my smultron from `cm-10.1_smultron-LX-20131104-NIGHTLY` to `cm-10.2_smultron-LX-20140112-NIGHTLY` and the corresponding `gapps-jb-20130813-lite-signed`, and unfortunately I'm now noticing the same thing. The messaging app seems to be wakelocking. I'm not doing any fancy mms texting. I'm not even texting. Just launching the messaging app seems to be enough to trigger this. Rebooting fixes it temporarily. I think killing the messaging app fixes it temporarily. However, I think receiving a text automatically launches the messaging app again, which seems to restore the wakelocking behaviour. Here's a screenshot of the battery manager in general, and the messaging app in particular:

![screenshot_2014-01-13-14-20-45](https://f.cloud.github.com/assets/799467/1907174/7859ce76-7cc3-11e3-9412-b36b2f99f5f6.png)

![screenshot_2014-01-13-14-20-57](https://f.cloud.github.com/assets/799467/1907175/78690d14-7cc3-11e3-830e-08a2a176c672.png)

These were screenshots from earlier today. Now, near the end of the day, I'm down to 60% battery, the system's been running for 6.5 hours, and the messaging app has been awake for 5.75 hours.

I'm not exactly sure of the standard way to generate and submit logs, but here is a logcat (generated in the terminal emulator using `logcat -d -f /sdcard/logcat.log *:V`) and dmesg (generated using `dmesg > /sdcard/dmesg`) from today, taken probably around the 4 hour mark since 100% battery:

https://gist.github.com/mspacek/d41a7f878e3c8140bc09

There seem to be several hits for `mms` in the logcat.log. I tend to keep wifi off. Note that I have one particularly long messaging thread with 6000+ messages in it, but that's nothing new for this phone. Also, I wiped cache and dalvik cache when updating the rom.

**Comment by mspacek** [comment]
I can confirm that killing the messaging app does indeed stop the rapid battery drain, and the messaging app's "keep awake" time stops increasing.

**Comment by mspacek** [comment]
Looks like this might be a known issue in Android 4.3, with some workarounds:

**Messaging app drains battery after 4.3 update**
https://code.google.com/p/android/issues/detail?id=58149

**Android 4.3 Bug - Messaging app draining my battery!**
http://www.reddit.com/r/Android/comments/1j7tzz/android_43_bug_messaging_app_draining_my_battery/

From what I can tell, turning off mms auto-retrieve in the messaging app didn't help in my case, but going through and deleting any recent mms messages seems to have fixed the problem for me! I think the culprit was a mass mms I sent out to a bunch of people on the winter solstice (Dec 21), some of which may have not gone through. Strange that the problem only showed up after upgrading to cm10.2 a couple days ago.
