### ISSUE TITLE
[11.0] mmc Data timeout cause system reload

### ISSUE THREAD

**Issue by SquallATF** [LegacyXperia/local_manifests#268]
Version : alphabuild 2 

I have create 3 partition on my 32g sd card 1 fat 2 ext4 3 swap and use link2sd to install more app, but I usually get follow error then system reload.
http://pastebin.com/GzHmsf5H

**Comment by mikeNG** [comment]
try alpha 3

**Comment by SquallATF** [comment]
still have problem but system not reload
http://pastebin.com/kkFtc5UQ

**Comment by mikeNG** [comment]
Please use pastebin or a similar service to post the logs. It's hard to read them here in github comments
Also, I could not reproduce the issue  with a partitioned sdcard.

Can you try a different sdcard or a different ROM?

**Comment by CTCaer** [comment]
Some insight on this. 
From this mmcblk0: mmc1:aaaa SU32G 29.7 GiB
I know that you have a Sandisk Ultra 32GB. Your SD card is dying or died.
Same problem to me. Random unmounts, mounts, corrupted SD, empty SD and many times like it's not there.
My sd? Sandisk ultra class10 32GB, Date: 10/2012, HW REv: 0x8
The unacceptable problem lies here: http://www.phonearena.com/news/SanDisk-says-it-produced-some-bad-32GB-and-64GB-microSD-cards_id40986
And believe me it's not only "some bad" (already have 2 of them). They are all of the 32GB/64GB because it's a manufacture problem.
That means that every one of them have a clock ticking to an end...

What you can do? Backup fat32 on your pc, make an image (to keep permissions and selinux contexts) of ext partitions.
Go to the store you bought it with your receipt and ID card and RMA it. They will give you right away a new one.
You lost receipt and not a named record of your purchase? RMA it through Sandisk. It will take 2 weeks to have a new one.

**Comment by mikeNG** [comment]
SD card issue.
