### ISSUE TITLE
[10.2] SD card can't be mounted on pc in recovery

### ISSUE THREAD

**Issue by n1kolaa** [LegacyXperia/local_manifests#33]
I compiled rom and kernel yesterday using your guide,and got problem with monting sd on pc,it wont mont it.. @mikeNG http://forum.xda-developers.com/showthread.php?t=2397249 this guide.
PHONE:ANZU
KERNEL:BUILDED YESTERDAY
ROMLBUILDED YESTERDAY
PC:ON WINDOWS 7
I got no problem with kernel builded 21.8.2013

**Comment by MIXTERek** [comment]
with latest nightly 28.09 the same issue in trying mount and after few seconds it is unmounted

**Comment by DanielMalmgren** [comment]
I've got the same symptoms on 20130828 on Urushi.

**Comment by n1kolaa** [comment]
@mikeNG this need to be revented on every phone to fix monting sd card or find anoder way :)
https://github.com/LegacyXperia/android_device_semc_anzu/commit/633273c86be45f746d09865eb4c35673fa6561fd

**Comment by mikeNG** [comment]
I don't know why but cwm mount works perfect on my phone since the first 10.2 build

**Comment by ghost** [comment]
Mounting SD in CWM still doesn't work on anzu (20131001).

**Comment by mikeNG** [comment]
can you provice any logs?

**Comment by ghost** [comment]
You mean this https://dl.dropboxusercontent.com/u/40426219/recovery.log?

**Comment by ghost** [comment]
It worked on CM10.1. I'm using everything stock without any modifications and its a clean install if that matters.

**Comment by mikeNG** [comment]
Can you provide a dmesg log from recovery too?

**Comment by MIXTERek** [comment]
you can find log from recovery heare: http://www.mixterek.boo.pl\recovery.log

**Comment by ghost** [comment]
I wasn't sure how to do this but here are these logs https://dl.dropboxusercontent.com/u/40426219/dmesg.txt https://dl.dropboxusercontent.com/u/40426219/dmesg2.txt maybe they're the same maybe not I don't really understand how this stuff works.

**Comment by ghost** [comment]
Oh and adb doesn't recognize my phone while in recovery but I still hope that there is something interesting in files posted above.

**Comment by mikeNG** [comment]
weird, adb should work in recovery...
so these 2 dmesg logs are not from recovery?

**Comment by ghost** [comment]
It doesn't work for me in recovery and when booting up kernel so these logs are taken when rebooting from recovery to system because that's as close as I could get. 
When connecting USB for the first time after booting recovery there is connect and then imidiately disconnect sound in windows when plugging in for the second time just plug in sound but there is no device recognized in device manager. When leaving phone connected there are random connect attempts but it doesn't work.

**Comment by mikeNG** [comment]
Any news on this? I still cannot reproduce it, mounting works perfect on all PCs I tried...

**Comment by djey47** [comment]
It works here too. Haida, latest RC.
I'm using USB mass storage in recovery to plug into PC with Ubuntu Linux.

**Comment by ghost** [comment]
Okay this is strange, apparently for some people it does work and for some it does not. I'm running  Build 20131204 - cm-10.2 on Anzu and am experiencing the same issue. I remember running into this problem before on some LX kernel builds (Cm10.1 and .2) and kernels like SuperFusion. I will try digging further into this any logs that could help ? 

Maybe it's USB driver related on the PC side. Running Windows 7 64bit professional here. (don't have the sony software installed, which provides some drivers).

Some additional infos. My build is a fresh build done in this order:
- wipe everything on old ROM (system,dalvik, cache,etc) but the sdcard (because of upper problem)
- fastboot erase boot
- fastboot flash boot boot.img
- install the ROM and GAPPS from sd card
- format sd card
- do first boot

**Comment by ghost** [comment]
I think it's Arc/Arc S only bug because people on other devices aren't experiencing problems with this feature. I remember that I used to copy new CM10.1 builds onto my phone this way but later after upgrading to CM10.2 I couldn't mount my SD anymore. The biggest problem is that I can't use ADB to take logs because my phone is not recognized in CWM or while booting kernel.
I'm on Win8 btw.

**Comment by ghost** [comment]
I have tried so many ROMs and Kernels in the past month, that I don't remember exact build numbers/kernels. I remember that there were 10.0 and 10.1 Kernels that had working Mass Transfer on CWM and some that did not. I will test and open an issue as soon as I get some more info about this.

**Comment by ghost** [comment]
FIX FOR MASS STORAGE IN CWM:

After lots of testing I found out that it's a PC side driver issue. I think this is "somehow" important so I'm poking you @mikeNG, sorry for the spam :) Feel free to add it to the FAQ.

Basically Windows is installing the wrong driver. It should be installing a "mass storage driver" and instead it's finding  a "Sony sa0102 - Android ADB Interface (Driver) " in Windows update and installing this one instead.

To fix it, I first did a manual driver cleanup just to make sure (don't think it's necesary) and then proceeded with a clean install. I had the Sony PC Companion, Update Service and Android SDK (Google USB drivers) installed.

Driver cleanup:
- Followed this: http://www.petri.co.il/removing-old-drivers-from-vista-and-windows7.htm, to show all installed drivers on my PC.
- Unplugged my device from the PC
- Open the Device Manager
- Uninstalled and Removed all Android ADB drivers under the "Sony sa 0102" category
- Uninstalled and Removed Xperia Arc S under the Portable Devices catergory.
- Uninstalled and Removed all "grayed out" generic and mass storage devices under the Universal Serial Bus controller category.
- Uninstalled and Removed the "Linux File-CD Gadget USB Device" under the Disk Drive category.

Now the driver installation:
- Booted into CWM and plugged the device
- Windows found the Arc S but wasn't able to find a driver so "failure of driver installation" I just ignored it.
- Mounted SD Card on CWM and now it starts installing a "mass storage driver" but ends up finding the "Sony sa0102 - Android ADB Interface (Driver)" and finishes the install successfuly.
- Rightclick the just installed Android ADB Interface (Driver), in the Device Manager
- Browser my computer for driver software
- Let me pick from a list of device drivers on my computer
- and change to USB Mass Storage device, and hit Next.
- The USB Mass Storage device driver gets installed along with a Linux File-CD Gadget USB Device.

The remaining drivers got installed after changing USB modes under settings in Android and the "missing Xperia Arc S" driver after installing the drivers needed for fastboot.

Now the SD Card mounts successfuly.

![mass_storage_fix](https://f.cloud.github.com/assets/6280154/1847955/cd9b4c0e-7672-11e3-9088-e89d4516d7f8.jpg)

Hope this helps,
~ska

**Comment by MardonHH** [comment]
I think only
"write /sys/class/android_usb/android0/functions mass_storage,adb"
needs to be added back to init.recovery.semc.rc to fix the bug

**Comment by mikeNG** [comment]
no
