### ISSUE TITLE
[cm11][coconut][build cm-11.0-20131225] apps dont work

### ISSUE THREAD

**Issue by fingerslip** [LegacyXperia/local_manifests#360]
Hello
- when I reboot I always get android upgrading
- Flipboard firefox don't work, they worked in previous build.
- I always get wifi on in battery stats, even if not on

Logs

https://www.dropbox.com/s/zg6085oxtq16i7p/2013-12-29-01-19-56.txt
https://www.dropbox.com/s/tay9gw020aigmha/2013-12-25-19-46-40.txt

**Comment by sidharthgtm** [comment]
Please wipe cache and dalvik cache and provide a fresh log.

**Comment by fingerslip** [comment]
Flipboard now works firefox still black screen
After reboot still get android is upgrading

Logs
https://www.dropbox.com/s/2y7b6kkxq7ulin5/2013-12-30-22-48-43.txt

**Comment by ksranjith786** [comment]
I believe you have to wipe entire data first and install the build. Also u should use gapps which is relevant to 4.4.2

I have faced all such problems while installing in Live with Walkman phone. My steps are as below.
1. In Bootloader, I unlocked it with the provided boot.img
2. In ROM mode, Wipe data/factory reset
3. (Optional) wipe cache, dalvik cache
4. Install ROM
5. Install GApps

**Comment by fingerslip** [comment]
errrrr i always use gapps for the correct version and I wiped format etc in first install of cm11 why should I always do that every time I install a new build if devs say not to wipe format etc..

**Comment by ksranjith786** [comment]
Though I use same gapps from this site, it doesnt work for me. I got a gapps which is specified for 4.4.2, and it worked for me.

**Comment by ketkul** [comment]
@fingerslip for WIFI always use battery try go to wifi advanced setting and uncheck "Scanning Always Available"
its solves mine...

**Comment by sidharthgtm** [comment]
ART is buggy.  Please use dalvik runtime.

**Comment by fingerslip** [comment]
I am not using art...

**Comment by ketkul** [comment]
I am using ART on my satsuma, and I think its has better battery life. I'm not facing android upgrading at bootscreen, only the first one I switched to ART. First boot to ART I am facing lot of force close on GoogleApps and Google play, but after reboot once more, everything works fine.

But I can confirm that firefox is also blackscreen. And I don't install many apps because ART take away almost 100Mb of my data partition. Will try later with link2SD.

I don't know about you but I'm always reflash the kernel and wipe everything before installing a new release, just in case something is changed. For your ~"wifi on in battery stats, even if not on"~ problem, uncheck "Scanning Always Available" at WIFI setting.

P.S Iam not complaining, just sharing my experience...
P.S.S Pardon my English ~

**Comment by mikeNG** [comment]
File separate issues for separate bugs
