### ISSUE TITLE
cant turn screen on from a locked state.

### ISSUE THREAD

**Issue by Aerotinge** [LegacyXperia/local_manifests#367]
To reproduce this issue, I do a clean install,disable "Display&light->Adaptive backlight" and "Buttons->Backlight",then enable Force gpu render.

While some of these conditions are met, the screen of smultron can't be on from a locked state.

However,the phone is still working, I have adb and VNC connection remaining working. Seems like only the screen refuse to display anything...

[EDIT:logcat.txt attached]
http://s000.tinyupload.com/index.php?file_id=63422951654527471424

Thank You.
Sayid.

**Comment by mikeNG** [comment]
never force gpu render

**Comment by Aerotinge** [comment]
ya I've turn it off and rebooted, but backlight settings still reproduce this issue...

**Comment by mikeNG** [comment]
provide logs when this happens

**Comment by mikeNG** [comment]
try latest build

**Comment by Aerotinge** [comment]
still broken, both build 20140207(cm10.2) &20140203(cm11) won't fix.

**Comment by mikeNG** [comment]
It's probably an issue with our legacy graphics code. Too hard to fix.
With no ION kernel this probably can't be fixed

**Comment by mikeNG** [comment]
Please try latest build and provide logs if this still happens

**Comment by zweif** [comment]
Sometimes I have a similar issue, without changing performance setings, and I don't know how to reproduce. Screen doesn't turn on and everything else seems to work, but I can't really test because I can't see anything. It's possible to start music with this headphone button and to access adb (and led works). Pressing home button turns on button backlight, but sometimes it seems to be "frozen" and I get no reaction to home button ore headphone button.
I have to reboot to get phone working again.
https://www.dropbox.com/s/ub5l4bd2j87tnjy/last_kmsg.txt

**Comment by theprov** [comment]
The same happens to me. I have urushi with cm11-20140620. It happens always I turn on from standby, screen (backlight) is on but is black. Touch works indeed.
To see something i have to push power on button a lot of times.
LOG
https://www.dropbox.com/s/e7bprg9ordh7849/bugreport2.zip

**Comment by mikeNG** [comment]
It's probably device-specific or panel-specific issue. Still hard to fix since logs don't include anything useful. I could not reproduce this issue in the past 7 months

**Comment by zweif** [comment]
My flex cable is broken, maybe my issue was related to that.
