### ISSUE TITLE
Cm11 / anzu  / 11-20131225 (restart problem)

### ISSUE THREAD

**Issue by luismytronic** [LegacyXperia/local_manifests#369]
when you restart or turn off your phone does not keep the background he had since returned to the original

**Comment by ketkul** [comment]
I don't have problem with background on my Satsuma, but the widget i placed gone after restart, and sometimes not so cant tell whats triggering it.

**Comment by ghost** [comment]
I had the Widget not saving problem when using Trebuchet as my default launcher on CM10.2. I noticed widgets disappearing on the homescreen page (max. pages 3, widgets on 1st page) if their coresponding app was hidden in the drawer, and after trebuchet was forced to reload completely (because of RAM getting allocated for another app) ... coincidence?

**Comment by ksranjith786** [comment]
On my Xperia Arc S, If I set max no,of rows as 6 in my Menu, once upon restarting its changing to 5 rows... This is not persistent everytime...
