### ISSUE TITLE
android wakeup cm-11.0-20140121-NIGHTLY-LegacyXperia-coconut

### ISSUE THREAD

**Issue by godlesplay** [LegacyXperia/local_manifests#432]
http://i60.tinypic.com/vzctpi.png
http://i57.tinypic.com/hvap80.png
Mike, as you can see in screeshoots, there are a lot of android wakeups, do you need any logs? if yes, tell me when I should make them and how
regards!

**Comment by timracer** [comment]
Join too

**Comment by mikeNG** [comment]
try latest build

**Comment by timracer** [comment]
Hello, Mike. In cm-11 nightly 01-21-2014 for xperia ray I noticed huge battery drain and I figured out that is because of mobile network settings. It is only 3g or 2g (non 3g/2g) there and when I set to 3g there is a huge battery drain, but when I set to 2g battery is ok! Perfectly ok! ) I hope you Will note this issue and hope it will be useful info for you. Keep it up!
