### ISSUE TITLE
Hallon - "Soft Reboot" will cause media storage FC

### ISSUE THREAD

**Issue by xange** [LegacyXperia/local_manifests#491]
Any sort of "soft reboot" using (xposed or anything else) or random soft reboot will cause media storage FC all the time whenever triggered (eg, apollo wont play any music, no songs will be showing in it) only reboot the phone in proper way will fix or quick reset (power + home)

later i will post the logcat of using xposed do soft reboot.

**Comment by xange** [comment]
sorry, can't use LX center to collect logs. and very hard to collect logs using adb shell also.... but the FC can be reproduce using xposed installer.

**Comment by sidharthgtm** [comment]
LOG FROM ST15i

D/FileUtils(17186): Trying to get UUID for /storage/sdcard0 

E/MediaProvider(17186): /storage/sdcard0 UUID: -1

I/Choreographer(17114): Skipped 325 frames!  The application may be doing too much work on its main thread.

E/MediaProvider(17186): Can't obtain external volume ID even though it's mounted.

D/AndroidRuntime(17186): Shutting down VM

**Comment by xange** [comment]
Additional: result also can be reproduce using Developer options > Launch Tools > Bad Behavior > Crash the system server.

**Comment by ghost** [comment]
where are you get [CM11 nightly 20140206 Hallon],In download page, i just see [CM11 nightly 20140203] ?

**Comment by xange** [comment]
In settings, build number really wrote "0206", but zip was "0203", how you want to report when there are things that is confusing you? and in download page (basketbuild) there are many directory, each folder for different phones, in that bracket i stated is CM11 nightly 20140206 (or 03, whichever you can understand for which build i'm using), as for HALLON, its phone model where which folder i entered in basketbuild to download. if you are really don't understand any of this, please, do some research before you ask any question here, quote from mike: "looking for the wrong thing will cost a lot precious time".

**Comment by ghost** [comment]
thx for reply, i just ask beacuse this version is full of question. so i
guess there are new version.

> sorry for my english £¬my native language isn¡®t english

2014-02-26 21:22 GMT+08:00 Xange notifications@github.com:

**Comment by sidharthgtm** [comment]
Seriously are we here to discuss the build number or version..  this bug is from the second KK build.  plz stick to topic else mike will close this bug report.

**Comment by A-n-D** [comment]
same on iyoken, this bug left behind after fixing for media storage fc problem.

**Comment by psyke83** [comment]
mikeNG,

I can reproduce this on smultron using your 20140203 build (haven't checked the later one yet). This issue also occurs on Samsung legacy devices that I maintain in the androidarmv6 project using the same storage configuration (primary physical only, non-emulated).

This is a quick and dirty workaround that should also work on the smultron: http://review.androidarmv6.org/#/c/6869/

If you or anyone can suggest a better method that doesn't involve hardcoding the device name, please let me know.

**Comment by xange** [comment]
problems still persist on Hallon using 20140319 nightly build

**Comment by A-n-D** [comment]
here r few logs, don't know it help or not, i took logs after phone crashed automatically and soft rebooted... and after soft reboot android.process.media fc pop ups again and again.. unmount and again mount sd card solved android.process.media fc problem. 

http://forum.xda-developers.com/showpost.php?p=51838370&postcount=3139

**Comment by xange** [comment]
issue reopened after tested on nightly 20140512 build. Issue still persist.... temporary workaround: remount sdcard.....

**Comment by psyke83** [comment]
Mike,

As I mentioned before, this issue should be affecting all CM11 devices that use a "physical primary only" storage configuration (see: https://source.android.com/devices/tech/storage/config-example.html ). 

My previous workaround that I referenced on the 31st of March is no longer effective. Another way around the problem is to modify the storage_list.xml configuration and set the sdcard as non-removable. See: http://review.androidarmv6.org/#/c/6896/

**Comment by xange** [comment]
@psyke83 if sdcard is set as non-removable, in settings is it still possible to unmount it? i think there are some user using multiple sdcard and also it is not safe to remove sdcard without unmount it. except that remove sdcard when phone is off...

**Comment by psyke83** [comment]
xange,

Unfortunately, it will not be possible. This workaround makes better sense on my device, as most users are utilizing either swap or a /sd-ext partition. This is relevant because the "unmount" button in the GUI will only unmount the mmcblk0p1 (sdcard) partition, but mmcblk0p2 (sd-ext) and mmcblk0p3 (swap) will be ignored. Under these circumstances, removing the card while a partition is in use can cause instability or possibly even hardware damage.

**Comment by mikeNG** [comment]
In some devices, the sd is accessible without removing the battery. Now one can unmount the sd before removing it, after the patch it won't be possible to unmount before removing. I think this will cause more damage than good...

**Comment by psyke83** [comment]
Mike,

Yes, it's only a workaround. Let's organize things a bit.
1. In vold, the extractMetadata() function sends the uuid to the framework, which is only done near the end of the mounting process for a volume: https://github.com/CyanogenMod/android_system_vold/blob/cm-11.0/Volume.cpp#L565
2. Here's the part of the framework that receives the uuid (from vold): https://github.com/androidarmv6/android_frameworks_base/blob/cm-11.0/services/java/com/android/server/MountService.java#L835
3. When the system_server crashes, the uuid is lost. Vold finds the mount still active after the framework runs passes the "vdc volume list" command.
4. Vold finds the daemon (and mount point) already active, so it doesn't attempt to mount anything.  This means that the extractMetadata function is not executed, meaning that the uuid is not sent to the framework again.
5. The framework restarts and MountService finds the daemon already mounted: https://github.com/androidarmv6/android_frameworks_base/blob/cm-11.0/services/java/com/android/server/MountService.java#L772
6. MediaProvider crashes with a NPE due to the mUuid being null.

So, we need to find a way to re-send the uuid to the framework when vold finds a volume/daemon already mounted. I've been testing a bit of code to do this, but it's not immediately obvious how to get the block device name from the mounted label (e.g. /storage/sdcard0) in order for the extractMetadata function to work correctly.

**Comment by psyke83** [comment]
Mike,

I uploaded a proper fix to gerrit. Please review when you have time:
http://review.cyanogenmod.org/#/c/64436/
http://review.cyanogenmod.org/#/c/64437/

**Comment by xange** [comment]
Fixed on latest nightly 20140531, closing this issue.... thanks.
