### ISSUE TITLE
Possible solution to wifi problems due to difference in kernel and wifi modules

### ISSUE THREAD

**Issue by amishmm** [LegacyXperia/local_manifests#55]
There are several users who complain about Wifi not working after kernel (boot.img) flash.

This is mostly due to Wifi modules are not inside boot.img but they are inside NIGHTLY (/system/lib/modules) zip.

If kernel version is version X but modules inside nightly are of version Y, wifi will not work.

If you integrate wifi module in boot.img (kernel) instead of nightly zip, this issue should possibly resolve on its own.

People will stop complaining about wifi not working and we do not have to keep asking them to flash the kernel inside the zip (although that is recommended)

This will also help in porting kernel (boot.img), trying different kernels etc. giving more flexibility.

**Comment by mikeNG** [comment]
This is not possible, it will increase size of the boot.img and people with bad blocks in boot partition won't be able to flash the kernels.

**Comment by amishmm** [comment]
But the total size of those files when zipped is just around 350kb. So initrd will increase from 3.75MB to little over 4MB.

I dont know if that increase too much? Just making a guess.

**Comment by mikeNG** [comment]
Most users with bad blocks can't flash a boot.img bigger than ~8mb

**Comment by amishmm** [comment]
Just a suggestion, may be u can move some other less used driver to /system/lib/modules and bring wifi drivers to kernel?

Because wifi probably is more important to have integrated support.

Just my suggestion, I have no idea how much that is possible and how easy or tough it is.

**Comment by maxfragg** [comment]
seriously, thats bulls**t, if the drivers load at all, the fact that they are modules, can not cause these problems

**Comment by pcfighter** [comment]
... so I'm closing this issue.

**Comment by amishmm** [comment]
@maxfragg Dont know what is the need cuss? This is not about wifi interruptions. Its about different issue. Its abt kernel boot image (initrd). Try loading different kernel in boot and different module in /system and u will realize what I am talking abt.

**Comment by pcfighter** [comment]
We can't do what you want, because people who can't flash 8M size boot WILL DEFINETLY WON'T use our kernels without modifications. Our solution allows use of our work with no problems, just have to flash new kernel included in zip. We can't provide better solution when we can't flash directly from recovery kernel image.

**Comment by mikeNG** [comment]
@pcfighter I agree. Using non-standard kernel is STRONGLY disadvised. Half of the posts with problems on xda seem to be related to using mixed kernel & builds. There are MANY changes that are coupled between the rom & the kernel, so if you use different kernels without the needed userspace changes, things will break.

```
#include <std_disclaimer.h>
/*
 * Your warranty is now void.
 *
 * I am not responsible for bricked devices, dead SD cards,
 * thermonuclear war, or you getting fired because the alarm app failed. Please
 * do some research if you have any concerns about features included in this ROM
 * before flashing it! YOU are choosing to make these modifications, and if
 * you point the finger at me for messing up your device, I will laugh at you.
 */
```

**Comment by amishmm** [comment]
Umm, its not about different non-standard kernel. Even if you use nAa kernel too, just increase in 0.0.1 version also breaks WIfi.

So that is why I suggested this. i.e. move some unimportant modules to /system and wifi modules to kernel. Atleast it will make sure that wifi always works regardless of userspace changes. I am assuming that for end-user functioning of wifi would be most important and first priority.

And most of complaints are abt wifi only that it stops functioning after flashing kernel. This will resolve those complaints. (Although I agree its recommended to flash provided kernel but we can still give user the option.)

I was trying to open initrd.img and check what is inside (asked abt it in XDA thread). But since its in lz4 format I could not open it. (I did not try to find hard abt lz4 reader)

Will wait for next version where you have switched to LZO format.

Thanks for your updates.

**Comment by mikeNG** [comment]
By non-standard I mean not using the exact same kernel from the exact same build. Build X should have kernel X, not Y. If a user uses a different kernel than the included from the exact same release, I simply ignore the bug reports.

For example in the next release, there are many changes at the keypads as they were rewritten from scratch. Now, if the users use an older kernel, keys might not be working at all. That is why I disagree to support non standard kernels.

Also, in order to integrate the kernel modules in the ramdisk, I need to switch a bunch of built-in drivers to modules and place them in system. This is difficult because there is not much I can turn into modules, most of the drivers are important and should be in kernel. I also need to mod the build system to copy the modules to ramdisk. Then we're starting to get away from standard AOSP/CM build system and I wouldn't like to do that.

The main issue is that many people get the idea wrong: I'm not providing a rom for everyday users. If you check xda, it's [DEV] not [ROM] I'm providing these builds just as a hobby and learning experience. Meaning, I don't want users in my rom that don't know the simple rule to always flash the kernel from each release. If there are such users, I don't want to support them because it's wasted time. It takes a few seconds to flash the kernel so there is no excuse for that. We have to live with the limitation of having to use fastboot.

This is open source, anyone who doesn't like what I'm doing can fork and do his own changes.
Don't get me wrong and think I'm angry, I'm just clarifying some things.

**Comment by amishmm** [comment]
Ok. I know you are just clarifying and thank you for your replies. (Words dont have face expression / pitch and tone of voice, so some may find some words strong / angry while they are not so!)

These discussions are worthy because it shares knowledge. Since I am from linux background, I try to go in every detail. So some may find it annoying. (I have realized that on XDA!)

I cud not check initrd, so I cud not go much in detail what is inside. (Again) I will do that in next release.

**Comment by amishmm** [comment]
I could now check initrd and have suggestion on how we can reduce size of boot.img by about 1.2MB.

Please see:
https://github.com/LegacyXperia/local_manifests/issues/66
