### ISSUE TITLE
[11-20140122][hallon]Touch not working after sleep

### ISSUE THREAD

**Issue by nutterbg** [LegacyXperia/local_manifests#559]
Hi,

I have searched for a similar issue in both the closed and open tickets, but possibly the closest I've come to is this:
https://github.com/LegacyXperia/local_manifests/issues/218
The problem I'm experiencing is that the touch occasionally stops working when I wake up the phone. The buttons work, and I can put it back to sleep, or open the power menu, however touch doesn't come back, and I'm stuck on the lock screen, until I pull the battery.

Mike,
Is this something that you are aware of? Perhaps something that wouldn't be present in one of the nightlies, since I realize I'm using a fairly old build by now?

Sorry for not providing logs, but I'll do my best to pull some dmesg the next time I replicate this issue at home. Bear with me here.
## Thanks

nutter

**Comment by sean024** [comment]
Hi,

I just installed CM11 yesterday on my Live with Walkman (WT19i) and I've been experiencing the same issue.  I'm not sure if this issue is related, but since it's the touch that's giving the problem I thought it must be.

I've noticed that when I've got the USB charger cable plugged in the touch would go haywire.  For example if I try to open an app that's placed at the centre of the screen, it would suddenly click on another app except that one, on the same page.

Also the Back touch button on the phone would stop working when it's plugged in.  I would have to restart the phone again without the USB charger cable plugged in and then it works just fine.

Please look into this issue.

Thanks,

**Comment by nutterbg** [comment]
Hi Sean,

You may be right about the charger. I haven't been able to get it to crash again since last night, and the last time I did was in fact on the charger, so this may be related indeed. I have to head out for the day, so I probably won't be able to charge again for a few hours, but I'll keep that in mind for when I do.

nutter

**Comment by xange** [comment]
close issue if this is solved. thanks.

**Comment by nutterbg** [comment]
It hasn't happened again. Really weird.
If it does, and I get logs, I'll open up a new ticket, referencing this one.

Thx.
