### ISSUE TITLE
Proximity sensor fix?

### ISSUE THREAD

**Issue by amishmm** [LegacyXperia/local_manifests#72]
Whenever we receive a call or make a call Proximity sensor detects that ear is touching the phone and switches of the screen to avoid accidental touches  or screen.

For wt19i / coconut it appears that proximity sensor is not quick enough.

There is a fix for smultron but it appears that it somehow works for coconut too.

This requires following changes to hw_config.sh file.

 *)
  val_cycle=0
  val_nburst=26
  val_freq=0
  val_threshold=2
  val_filter=0

I have tested this fix for abt 15-20 days and seems to work fine.

Other coconut users on XDA have also reported success with this fix.

So may be we can apply this fix.

thanks.

**Comment by amishmm** [comment]
Updated to 20131001 Nightly.

Looks like this fix is no more needed.

Finger test (by putting finger 1 cm above the sensor) is successful.

Screen switches off properly and immediately.

**Comment by mikeNG** [comment]
Not needed

**Comment by amishmm** [comment]
Actually this bug exists (or re-appeared in recent release).

Random screen touches during call still keeps happening (without above fix)

**Comment by mikeNG** [comment]
well can you try again with the fix?
if it's working I'll push it for all devices

**Comment by amishmm** [comment]
Yes fix works.

The new release works but sensitivity is even better if you apply above fix.

With above fix phone detects ear faster hence screen goes off earlier (on time)

Without fix if you are fast person and immediately take phone near the ear OR if your phone twists slightly when talking, screen turns on and accidental touch happens.

Btw fix as mentioned by others is only for coconut and smultron (i think), Dont know if it will work for all devices.

Thanks for your excellent development and support.

**Comment by MIXTERek** [comment]
tested form mango it work's excelent

**Comment by mikeNG** [comment]
Added for mango & coconut. Don't know if this is needed for any other devices

**Comment by amishmm** [comment]
Great Thanks!

I am on CM11.0 and fix works there too. May be you can apply fix for CM11 too.

**Comment by mikeNG** [comment]
I'll do

**Comment by Micha-Btz** [comment]
i have tried this settings on my mango, but it make this worster than before.
I just changes the hw_config file by hand an reboot the device. More changes are dedicated to the git commit not necessary. 
During the call i was relay deep in the config changes only by touch with my ear.
Is there a domcumentation for this so that i can play with these?

**Comment by mikeNG** [comment]
So... I guess it's a device specific issue and there is no way to fix it. I will probably revert the fixes and someone has to create some flashable zips of the fix if needed.

@Micha-Btz the only documentation is the comments in lines 32-36 here https://github.com/LegacyXperia/android_device_semc_mango/blob/cm-10.2/rootdir/system/etc/hw_config.sh#L32

**Comment by Micha-Btz** [comment]
echo $val_nburst > $dev/nburst # Number of pulses in burst. Valid range is 0 - 15.

so  val_nburst=26 can be correct i think

**Comment by mikeNG** [comment]
according to sony, 26 is valid only for smultron, but it seems to work on some coconuts too

**Comment by Micha-Btz** [comment]
can i simulate a call to test my config?

**Comment by Micha-Btz** [comment]
hm, i have experiment yesterday with i change the settings, but i have found no working solution.
This is tricky because i don't know which parameter i should change and i what direction.

The question for me is, the old settings was about half a year and worked well, that is changed in code thats not work anymore?
Is the proximity sensor only work by an active call? Or when a call is incomming too?
The screen should go dark when i hide the two sensors at the top of the phone, but this isn't   happen.

**Comment by Micha-Btz** [comment]
hm, some things are really strange here i think.

http://pastebin.com/60vADZ2C

It is not possible to change things an run the hw_config.sh script to test it?
I also remove the slash for the line 

"# Proximity sensor configuration
dev=/sys/bus/i2c/devices/0-0054/"
because the values are also have this, so that the output is
/sys/bus/i2c/devices/0-0054//cycle doesn't know if it care.

**Comment by Micha-Btz** [comment]
i have played today with these app https://play.google.com/store/apps/details?id=com.tigermonster.proxfinder&hl=de
and with this settings

val_cycle=0
val_nburst=26
val_freq=0
val_threshold=2
val_filter=0
the proximity sensor doesn't work. so i have used te orginal settings from sony to play around and this works.

**Comment by mikeNG** [comment]
Ok so I'll revert the changes...

**Comment by amishmm** [comment]
This could be device (manufacturing batch) specific issue.

So I guess reverting patch is right thing. Those having issues can apply the fix.

For me both settings work but without FIX there are false touches (if your hand goes fast to ears). With FIX it just works without issues.
