### ISSUE TITLE
screen brightness initially very low on mango (Xperia Mini Pro), cm11-20140718

### ISSUE THREAD

**Issue by hannob** [LegacyXperia/local_manifests#728]
I just flashed the latest cm11 snapshot on my Xperia Mini Pro (mango). On bootup the screen brightness was very low, almost unusable.

I was later able to change the brightness without problems, however it made doing the initial configuration and setup a bit tricky and inconvenient, as I was barely able to see anything on the screen (and found no way to change it before I did the initial setup).

**Comment by hegyre** [comment]
Hi, Got the same issue.
Just flash cm11-20140718 (had official ICS .587 before), and brightness was very low.
I suspect the auto brightness, as I had to de-activate it in order to see lighter.

**Comment by mikeNG** [comment]
Literally nothing changed regarding light sensor in the past 4-5 months, so I don't know why you have this issue. I wasn't able to reproduce it on any of my 5 devices

**Comment by leadenmoth** [comment]
I can confirm that the initial brightness on mango is very low, and it indeed has been like that for months. The default auto-brightness settings are almost unusable, even in complete darkness. It wouldn't have been much of a problem, since there's a menu to edit the triggers, but the tiny mango screen makes that menu really hard to use, so yeah, if the default settings were a bit brighter, new users wouldn't have been as shocked. It's a very minor problem, but it's kind of the first thing newcomers notice.

**Comment by Tanzbaerli** [comment]
I can confirm this bug on the builds  
cm-11-20140816-UNOFFICIAL-LegacyXperia-mango and
cm-11-20140907-UNOFFICIAL-LegacyXperia-mango

no big problem but annoying

**Comment by foresto** [comment]
I have this problem on cm-11-20141224-UNOFFICIAL-LegacyXperia-mango.

Moreover, the light sensor settings report 0 lux even with ambient light in a room during the day. It takes a very bright room to get more than 100-200 lux. Could there be a problem with the software that reads the light sensor?

**Comment by mikeNG** [comment]
No logs. Can't reproduce in any of my 9 devices
