### ISSUE TITLE
[AOSP][Iyokan] Front Keys + Keyboard lights never turn off on AOSP 5.1.1

### ISSUE THREAD

**Issue by dafuki** [LegacyXperia/local_manifests#924]
The Front Keys + Keyboard lights never turn off, eating my battery.
Also, the AOSP 5.1.1 is far faster than CM12.0 on my iyokan, but is really hard to get used to so I'm just downgrading th CM12.0.

Respect for all the hard work.

P.S, Any ETA on the CM12.1 nightly?

**Comment by legas1** [comment]
If you want, you can turn it off in settings.

**Comment by dafuki** [comment]
You mean permanently? How do i do that?

**Comment by legas1** [comment]
Well you will find it in AOSP settings or Screen settings, I dont remember, because I changed to CM11 again.

**Comment by tangtony** [comment]
For AOSP: Its under LegacyXperiaAOSP Settings > Button Backlight Brightness

**Comment by Neuen1** [comment]
I'm having this bug on my Mango too. I can turn them off but then I can't type in the dark

**Comment by GauriSpears** [comment]
Confirm the bug for AOSP 5.1.1 beta 2 for Mango. Auto brightness control is not perfect, but working. Buttons and keyboard backlight auto control NOT working.
It's strange that:
1. there is no config of LMU AS3676 in /system/etc/hw_config.sh as it usually should be;
2. there is no als in /sys/devices/i2c-0/0-0040/leds/lcd-backlight, /sys/devices/i2c-0/0-0040/leds/keyboard-backlight and /sys/devices/i2c-0/0-0040/leds/button-backlight.

**Comment by GauriSpears** [comment]
I've investigated android sources and came to conclusion that the problem is a bit deeper. In Android 4.0.4 com.android.server.PowerManagerService module controlled all light activity, including buttons and keyboard backlight. In 4.4.4 and 5.1.1 screen backlight is controlled by DisplayPowerController and leds are switched on/off by NotificationManagerService and BatteryService. It looks like autocontrol of buttons and keyboard backlight is not run by android anymore. Maybe device vendors have to implement their own services. Does anybody know?

**Comment by mikeNG** [comment]
AOSP doesn't support hardware keyboards or buttons since a long time, but in CM there are patches that fix all the light issues. Just need to find them and cherry-pick them to AOSP

**Comment by GauriSpears** [comment]
Mike, you are right! I've just had a look into PowerManagerService of CM 12.1. It contains updateUserActivitySummaryLocked method which performs necessary buttons and keyboard operations.
