### ISSUE TITLE
[CM 12.1] [iyokan] Suddenly very slow, zram allocation errors and "Write-error on swap-device"

### ISSUE THREAD

**Issue by EreMaijala** [LegacyXperia/local_manifests#947]
It has happened to me a couple of times that the phone running build 20150606 has crawled to almost a halt, e.g. I couldn't answer an incoming phone call as the UI didn't come up at all and opening Settings from the drawer taking half a minute. I took logs and an obvious possible problem is:

<6>[32676.649259] zram: Error allocating memory for compressed page: 33873, size=4096
<1>[32676.649381] Write-error on swap-device (254:0:270984)
<6>[32679.344816] zram: Error allocating memory for compressed page: 39900, size=2020
<1>[32679.344938] Write-error on swap-device (254:0:319200)
...hundreds of more Write-errors after these...

Logs:
dmesg: http://pastebin.com/vFV6syVy
event: http://pastebin.com/wGdCUyG2
logcat: http://pastebin.com/Mwv7Eyw9

**Comment by rtsui-harmonicinc** [comment]
there are 2 solutions. 
1/ CHange io governor to bfq
2/ lower swappiness

**Comment by gabri-hell** [comment]
Problem is GAPPS or conflict with GAPPS, especially the Launcher...
My system had become totally unstable and a real turtle so I did few tests yesterday to target the troublemaker.
To have again a faster and healthy system, reload last build 20150607 and put Mini GAPPS instead of Std GAPPS (http://forum.xda-developers.com/android/apps-games/hdpi-google-apps-5-1-t3066172)
Boot the base ROM without GAPPS to persuade you..., you'll see everything works well.
I think there's a problem with the Launcher because it seemed restart constantly and was often asking me to enter pin 2 times of was giving me black screens when swapping between apps.
To my level I don't have the skills to say more, sorry...
Overall, CM-12.1 is a bit slower than CM-11 but surely improve in the future, let's be patient !

**Comment by EreMaijala** [comment]
Whatever GApps does still shouldn't cause ZRAM failures, I think. And the phone's been running quite well for many days with standard GApps installed. This problem is intermittent. I suppose you might be seeing something else.

**Comment by gabri-hell** [comment]
My phone has become unstable from the 2nd boot after GAPPS installation.
Finally I totally removed GAPPS and the system is unrecognizable, very fast and lively.
I replaced Gapps by alternative apps, I just lack my sync contacts.
For the moment it will remain like that, unbearable to "drive with handbrake" !

**Comment by rtsui-harmonicinc** [comment]
#885
