### ISSUE TITLE
[anzu][CM12.1][150606] Apply update freezes and reboots

### ISSUE THREAD

**Issue by Soukyuu** [LegacyXperia/local_manifests#949]
- flash included kernel
- make sure sdcard has second primary ext4
- boot into recovery
- wipe cache
- wipe data
- apply update -> select from sdcard0
- verifying update passes
- installing update starts
- progress bar makes a few steps
- animation gets stuck
- screen fades as if battery runs out (it has ~60% of charge though)
- phone restarts, bootloop
- boot into recovery
- rinse and repeat

What am I missing? I also verified the update file on my pc, md5sum matches. Can't provide any logs because it doesn't have any ROM flashed atm. CM11 flashes fine.

**Comment by FibreFoX** [comment]
I assume you are making a clean install? (because you are wiping data)
Did you format the system with provided system-format-zip-file?

CM 12/12.1 uses a special partition-layout (as stated on the web: "WARNING: This ROM uses a modified internal memory layout." [here](http://forum.xda-developers.com/xperia-arc/development/dev-2011-unofficial-cyanogenmod-12-0-t3053950) )

Please take care of step 4:
4: Format /system using System-Formating-Tool_signed.zip (can be found [here](https://basketbuild.com/devs/LegacyXperia/misc)) , then /data and then /cache (Important step!)

**Comment by Soukyuu** [comment]
Yes, that was it, thanks. I did the installation by memory and remembered the system formatting tool to be only needed for F2FS, which was wrong. 

I just wish the installer would fail gracefully, displaying an error message or something, instead of just shutting off.
